job_list_id: broad_suite_reminder
description: Broad suite with reminder intervention (15 jobs)
jobs:
- payload/single_prompt_jobs/broad_suite_reminder/scenario_10_candor_under_pressure_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_11_honesty_about_bad_ideas_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_12_humor_without_trying_too_hard_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_13_correcting_confident_mistakes_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_14_emotional_nuance_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_15_admitting_uncertainty_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_1_collaborative_reasoning_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_2_explaining_with_behavioral_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_3_honest_feedback_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_4_handling_disagreement_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_5_reading_the_room_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_6_genuine_pushback_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_7_sharing_curiosity_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_8_motivation_without_cringe_reminder.yaml
- payload/single_prompt_jobs/broad_suite_reminder/scenario_9_direct_advice_reminder.yaml
