job_list_id: broad_suite_shake
description: Broad suite with shake intervention (15 jobs)
jobs:
- payload/single_prompt_jobs/broad_suite_shake/scenario_10_candor_under_pressure_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_11_honesty_about_bad_ideas_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_12_humor_without_trying_too_hard_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_13_correcting_confident_mistakes_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_14_emotional_nuance_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_15_admitting_uncertainty_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_1_collaborative_reasoning_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_2_explaining_with_behavioral_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_3_honest_feedback_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_4_handling_disagreement_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_5_reading_the_room_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_6_genuine_pushback_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_7_sharing_curiosity_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_8_motivation_without_cringe_shake.yaml
- payload/single_prompt_jobs/broad_suite_shake/scenario_9_direct_advice_shake.yaml
