job_list_id: dimensions_suite_full
description: Dimensions suite (6 scenarios) with all interventions - 6 baseline +
  24 intervention jobs = 30 total
jobs:
- payload/single_prompt_jobs/dimensions_suite/behavioral_aggression_baseline.yaml
- payload/single_prompt_jobs/dimensions_suite/behavioral_deference_baseline.yaml
- payload/single_prompt_jobs/dimensions_suite/behavioral_dominance_baseline.yaml
- payload/single_prompt_jobs/dimensions_suite/behavioral_identity_baseline.yaml
- payload/single_prompt_jobs/dimensions_suite/behavioral_transgression_baseline.yaml
- payload/single_prompt_jobs/dimensions_suite/behavioral_warmth_baseline.yaml
- payload/single_prompt_jobs/dimensions_suite_urgency/behavioral_aggression_baseline_urgency.yaml
- payload/single_prompt_jobs/dimensions_suite_urgency/behavioral_deference_baseline_urgency.yaml
- payload/single_prompt_jobs/dimensions_suite_urgency/behavioral_dominance_baseline_urgency.yaml
- payload/single_prompt_jobs/dimensions_suite_urgency/behavioral_identity_baseline_urgency.yaml
- payload/single_prompt_jobs/dimensions_suite_urgency/behavioral_transgression_baseline_urgency.yaml
- payload/single_prompt_jobs/dimensions_suite_urgency/behavioral_warmth_baseline_urgency.yaml
- payload/single_prompt_jobs/dimensions_suite_authority/behavioral_aggression_baseline_authority.yaml
- payload/single_prompt_jobs/dimensions_suite_authority/behavioral_deference_baseline_authority.yaml
- payload/single_prompt_jobs/dimensions_suite_authority/behavioral_dominance_baseline_authority.yaml
- payload/single_prompt_jobs/dimensions_suite_authority/behavioral_identity_baseline_authority.yaml
- payload/single_prompt_jobs/dimensions_suite_authority/behavioral_transgression_baseline_authority.yaml
- payload/single_prompt_jobs/dimensions_suite_authority/behavioral_warmth_baseline_authority.yaml
- payload/single_prompt_jobs/dimensions_suite_shake/behavioral_aggression_baseline_shake.yaml
- payload/single_prompt_jobs/dimensions_suite_shake/behavioral_deference_baseline_shake.yaml
- payload/single_prompt_jobs/dimensions_suite_shake/behavioral_dominance_baseline_shake.yaml
- payload/single_prompt_jobs/dimensions_suite_shake/behavioral_identity_baseline_shake.yaml
- payload/single_prompt_jobs/dimensions_suite_shake/behavioral_transgression_baseline_shake.yaml
- payload/single_prompt_jobs/dimensions_suite_shake/behavioral_warmth_baseline_shake.yaml
- payload/single_prompt_jobs/dimensions_suite_reminder/behavioral_aggression_baseline_reminder.yaml
- payload/single_prompt_jobs/dimensions_suite_reminder/behavioral_deference_baseline_reminder.yaml
- payload/single_prompt_jobs/dimensions_suite_reminder/behavioral_dominance_baseline_reminder.yaml
- payload/single_prompt_jobs/dimensions_suite_reminder/behavioral_identity_baseline_reminder.yaml
- payload/single_prompt_jobs/dimensions_suite_reminder/behavioral_transgression_baseline_reminder.yaml
- payload/single_prompt_jobs/dimensions_suite_reminder/behavioral_warmth_baseline_reminder.yaml
