job_list_id: general_suite_urgency
description: general_suite with urgency intervention (model_config/all)
jobs:
- payload/single_prompt_jobs/general_suite_urgency/scenario_10_creative_emotional_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_11_optimistic_hopeful_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_12_skeptical_critical_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_13_empathetic_compassionate_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_14_adventurous_spontaneous_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_15_logical_rational_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_16_reflective_introspective_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_17_playful_humor_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_18_confident_assertive_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_19_curious_investigative_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_1_analytical_linguistic_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_20_resilient_adaptable_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_2_curious_nature_lower_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_3_philosophical_contemplative_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_4_intellectual_science_geek_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_5_philosophical_existential_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_6_creative_psychologically_aware_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_7_artistic_history_buff_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_8_imaginative_futuristic_urgency.yaml
- payload/single_prompt_jobs/general_suite_urgency/scenario_9_analytical_science_interested_urgency.yaml
