job_list_id: all_suites_baseline_telemetryV3
description: All suites - baseline telemetry V3 (51 jobs)
jobs:
- payload/single_prompt_jobs/all_suites_telemetryV3/16_broad_15_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/17_broad_1_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/18_broad_2_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/19_broad_3_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/20_broad_4_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/21_broad_5_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/22_broad_6_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/23_broad_7_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/24_broad_9_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/25_dimensions_aggression_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/26_dimensions_deference_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/27_dimensions_dominance_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/28_dimensions_identity_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/29_dimensions_transgression_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/30_dimensions_warmth_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/31_general_typical_v2_10_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/32_general_typical_v2_11_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/33_general_typical_v2_12_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/34_general_typical_v2_13_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/35_general_typical_v2_14_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/36_general_typical_v2_15_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/37_general_typical_v2_16_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/38_general_typical_v2_17_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/39_general_typical_v2_18_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/40_general_typical_v2_19_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/41_general_typical_v2_1_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/42_general_typical_v2_20_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/43_general_typical_v2_2_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/44_general_typical_v2_3_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/45_general_typical_v2_4_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/46_general_typical_v2_5_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/47_general_typical_v2_6_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/48_general_typical_v2_7_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/49_general_typical_v2_8_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/50_general_typical_v2_9_telemetryV3.yaml
- payload/single_prompt_jobs/all_suites_telemetryV3/51_broad_8_telemetryV3.yaml
